// <auto-generated />
using META_TodoList.Data.cs.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace META_TodoList.Data.Migrations
{
    [DbContext(typeof(META_DBcontext))]
    [Migration("20230522033206_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("META_TodoList.Data.cs.Entities.AppConfig", b =>
                {
                    b.Property<int>("key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("key"));

                    b.Property<int>("value")
                        .HasColumnType("int");

                    b.HasKey("key");

                    b.ToTable("AppConfig", (string)null);
                });

            modelBuilder.Entity("META_TodoList.Data.cs.Entities.UserSignUp", b =>
                {
                    b.Property<string>("_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_pass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_repass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_submit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("_id");

                    b.ToTable("UserSignUp", (string)null);
                });

            modelBuilder.Entity("META_TodoList.Models.ToDoList_Model.ToDoTitle", b =>
                {
                    b.Property<string>("_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("User_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("_checkedtitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("_id");

                    b.HasIndex("User_Id");

                    b.ToTable("ToDoTitle", (string)null);
                });

            modelBuilder.Entity("META_TodoList.Models.ToDoList_Model.ToDoTitle", b =>
                {
                    b.HasOne("META_TodoList.Data.cs.Entities.UserSignUp", "users")
                        .WithMany("titles")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("users");
                });

            modelBuilder.Entity("META_TodoList.Data.cs.Entities.UserSignUp", b =>
                {
                    b.Navigation("titles");
                });
#pragma warning restore 612, 618
        }
    }
}
